version: '3'
services:
  web:
    build: .
    ports:
       - "3001:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/proyecto-test
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
